"""create core schema

Revision ID: ab57afc7b327
Revises:
Create Date: 2026-08-01 23:20:20.355210
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ab57afc7b327"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("sensitive", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_app_settings")),
    )
    op.create_table(
        "credentials",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password", sa.Text(), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("session_token", sa.Text(), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("id_token", sa.Text(), nullable=True),
        sa.Column("device_id", sa.String(length=255), nullable=True),
        sa.Column("cookie_header", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("email", name=op.f("pk_credentials")),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                "canceled",
                name="job_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_jobs_claim", ["status", "available_at", "priority", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_jobs_kind"), ["kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_jobs_lease_expires_at"), ["lease_expires_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_jobs_lease_owner"), ["lease_owner"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_status"), ["status"], unique=False)

    op.create_table(
        "kakao_card_batches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ready", "consumed", "archived", name="card_batch_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kakao_card_batches")),
    )
    with op.batch_alter_table("kakao_card_batches", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_kakao_card_batches_status"), ["status"], unique=False)

    op.create_table(
        "outlook_accounts",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password", sa.Text(), nullable=True),
        sa.Column("client_id", sa.String(length=255), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column(
            "mail_type",
            sa.Enum("outlook", "link", name="mail_type", native_enum=False),
            nullable=False,
        ),
        sa.Column("mail_url", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "available", "in_use", "done", "failed", name="account_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("email", name=op.f("pk_outlook_accounts")),
    )
    with op.batch_alter_table("outlook_accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_outlook_accounts_status"), ["status"], unique=False)

    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "paused",
                "completed",
                "failed",
                "canceled",
                name="pipeline_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("target_count", sa.Integer(), nullable=False),
        sa.Column("kakao_enabled", sa.Boolean(), nullable=False),
        sa.Column("config_snapshot", sa.JSON(), nullable=False),
        sa.Column("scheduled_count", sa.Integer(), nullable=False),
        sa.Column("registered_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("kakao_task_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_runs")),
    )
    with op.batch_alter_table("pipeline_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pipeline_runs_status"), ["status"], unique=False)

    op.create_table(
        "registration_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                "canceled",
                name="registration_run_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("error_category", sa.String(length=64), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("config_snapshot", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registration_runs")),
    )
    with op.batch_alter_table("registration_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_registration_runs_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("ix_registration_runs_status"), ["status"], unique=False)

    op.create_table(
        "job_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_events_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_events")),
        sa.UniqueConstraint("job_id", "sequence", name="uq_job_events_job_sequence"),
    )
    with op.batch_alter_table("job_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_job_events_job_id"), ["job_id"], unique=False)

    op.create_table(
        "kakao_cards",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["kakao_card_batches.id"],
            name=op.f("fk_kakao_cards_batch_id_kakao_card_batches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kakao_cards")),
        sa.UniqueConstraint("batch_id", "position", name="uq_kakao_cards_batch_position"),
        sa.UniqueConstraint("code", name=op.f("uq_kakao_cards_code")),
    )
    with op.batch_alter_table("kakao_cards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_kakao_cards_batch_id"), ["batch_id"], unique=False)

    op.create_table(
        "pipeline_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pipeline_run_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("account_email", sa.String(length=320), nullable=True),
        sa.Column("registration_run_id", sa.String(length=36), nullable=True),
        sa.Column("card_code_snapshot", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled",
                "registering",
                "registered",
                "submitting",
                "completed",
                "skipped",
                "failed",
                name="pipeline_item_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("eligibility_state", sa.String(length=64), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"],
            ["pipeline_runs.id"],
            name=op.f("fk_pipeline_items_pipeline_run_id_pipeline_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["registration_run_id"],
            ["registration_runs.id"],
            name=op.f("fk_pipeline_items_registration_run_id_registration_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_items")),
        sa.UniqueConstraint("pipeline_run_id", "position", name="uq_pipeline_items_run_position"),
    )
    with op.batch_alter_table("pipeline_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pipeline_items_account_email"), ["account_email"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_pipeline_items_pipeline_run_id"), ["pipeline_run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_pipeline_items_registration_run_id"),
            ["registration_run_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_pipeline_items_status"), ["status"], unique=False)

    op.create_table(
        "kakao_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("upstream_job_id", sa.String(length=255), nullable=False),
        sa.Column("pipeline_run_id", sa.String(length=36), nullable=True),
        sa.Column("pipeline_item_id", sa.String(length=36), nullable=True),
        sa.Column("card_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "extracting",
                "done",
                "failed",
                "canceled",
                name="kakao_task_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("payment_status", sa.String(length=64), nullable=True),
        sa.Column("card_charged", sa.Boolean(), nullable=True),
        sa.Column("payment_url", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("upstream_payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["kakao_cards.id"],
            name=op.f("fk_kakao_tasks_card_id_kakao_cards"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_item_id"],
            ["pipeline_items.id"],
            name=op.f("fk_kakao_tasks_pipeline_item_id_pipeline_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"],
            ["pipeline_runs.id"],
            name=op.f("fk_kakao_tasks_pipeline_run_id_pipeline_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kakao_tasks")),
    )
    with op.batch_alter_table("kakao_tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_kakao_tasks_card_id"), ["card_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_kakao_tasks_email"), ["email"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_kakao_tasks_payment_status"), ["payment_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_kakao_tasks_pipeline_item_id"), ["pipeline_item_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_kakao_tasks_pipeline_run_id"), ["pipeline_run_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_kakao_tasks_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_kakao_tasks_upstream_job_id"), ["upstream_job_id"], unique=True
        )

    op.create_table(
        "pipeline_card_allocations",
        sa.Column("pipeline_run_id", sa.String(length=36), nullable=False),
        sa.Column("card_id", sa.String(length=36), nullable=False),
        sa.Column("allocated_count", sa.Integer(), nullable=False),
        sa.Column("created_count", sa.Integer(), nullable=False),
        sa.Column("duplicate_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["kakao_cards.id"],
            name=op.f("fk_pipeline_card_allocations_card_id_kakao_cards"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"],
            ["pipeline_runs.id"],
            name=op.f("fk_pipeline_card_allocations_pipeline_run_id_pipeline_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "pipeline_run_id", "card_id", name=op.f("pk_pipeline_card_allocations")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pipeline_card_allocations")
    with op.batch_alter_table("kakao_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kakao_tasks_upstream_job_id"))
        batch_op.drop_index(batch_op.f("ix_kakao_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_kakao_tasks_pipeline_run_id"))
        batch_op.drop_index(batch_op.f("ix_kakao_tasks_pipeline_item_id"))
        batch_op.drop_index(batch_op.f("ix_kakao_tasks_payment_status"))
        batch_op.drop_index(batch_op.f("ix_kakao_tasks_email"))
        batch_op.drop_index(batch_op.f("ix_kakao_tasks_card_id"))

    op.drop_table("kakao_tasks")
    with op.batch_alter_table("pipeline_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pipeline_items_status"))
        batch_op.drop_index(batch_op.f("ix_pipeline_items_registration_run_id"))
        batch_op.drop_index(batch_op.f("ix_pipeline_items_pipeline_run_id"))
        batch_op.drop_index(batch_op.f("ix_pipeline_items_account_email"))

    op.drop_table("pipeline_items")
    with op.batch_alter_table("kakao_cards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kakao_cards_batch_id"))

    op.drop_table("kakao_cards")
    with op.batch_alter_table("job_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_events_job_id"))

    op.drop_table("job_events")
    with op.batch_alter_table("registration_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_registration_runs_status"))
        batch_op.drop_index(batch_op.f("ix_registration_runs_email"))

    op.drop_table("registration_runs")
    with op.batch_alter_table("pipeline_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pipeline_runs_status"))

    op.drop_table("pipeline_runs")
    with op.batch_alter_table("outlook_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outlook_accounts_status"))

    op.drop_table("outlook_accounts")
    with op.batch_alter_table("kakao_card_batches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kakao_card_batches_status"))

    op.drop_table("kakao_card_batches")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_jobs_lease_owner"))
        batch_op.drop_index(batch_op.f("ix_jobs_lease_expires_at"))
        batch_op.drop_index(batch_op.f("ix_jobs_kind"))
        batch_op.drop_index("ix_jobs_claim")

    op.drop_table("jobs")
    op.drop_table("credentials")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
