/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * GPT Auto Register
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query"

import { orvalRequest } from "../lib/api-client"
export type MailType = (typeof MailType)[keyof typeof MailType]

export const MailType = {
  outlook: "outlook",
  link: "link",
} as const

export type AccountStatus = (typeof AccountStatus)[keyof typeof AccountStatus]

export const AccountStatus = {
  available: "available",
  in_use: "in_use",
  done: "done",
  failed: "failed",
} as const

export interface AccountDetail {
  email: string
  mail_type: MailType
  status: AccountStatus
  claimed_at: string | null
  finished_at: string | null
  failure_reason: string | null
  created_at: string
  updated_at: string
  password: string | null
  client_id: string | null
  refresh_token: string | null
  mail_url: string | null
}

export interface AccountSummary {
  email: string
  mail_type: MailType
  status: AccountStatus
  claimed_at: string | null
  finished_at: string | null
  failure_reason: string | null
  created_at: string
  updated_at: string
}

export interface AccountListResponse {
  items: AccountSummary[]
  total: number
  limit: number
  offset: number
}

export type AccountMaintenanceAction =
  (typeof AccountMaintenanceAction)[keyof typeof AccountMaintenanceAction]

export const AccountMaintenanceAction = {
  reset_failed: "reset_failed",
  release_stale: "release_stale",
  delete_status: "delete_status",
} as const

export interface AccountMaintenanceRequest {
  action: AccountMaintenanceAction
  status?: AccountStatus | null
  /**
   * @minimum 1
   * @maximum 1440
   */
  stale_minutes?: number
}

export interface AccountMaintenanceResponse {
  processed: number
  skipped?: number
}

export interface AccountStats {
  total: number
  available: number
  in_use: number
  done: number
  failed: number
}

export type BulkAccountAction =
  (typeof BulkAccountAction)[keyof typeof BulkAccountAction]

export const BulkAccountAction = {
  release: "release",
  reset: "reset",
  delete: "delete",
} as const

export interface BulkAccountRequest {
  action: BulkAccountAction
  /** @minItems 1 */
  emails: string[]
}

export interface BulkAccountResponse {
  processed: number
  skipped: number
}

export type BulkCardAction =
  (typeof BulkCardAction)[keyof typeof BulkCardAction]

export const BulkCardAction = {
  activate: "activate",
  deactivate: "deactivate",
  delete: "delete",
} as const

export interface BulkCardRequest {
  action: BulkCardAction
  /** @minItems 1 */
  card_ids: string[]
}

export interface BulkCardResponse {
  processed: number
  skipped: number
}

export type BulkPipelineAction =
  (typeof BulkPipelineAction)[keyof typeof BulkPipelineAction]

export const BulkPipelineAction = {
  cancel: "cancel",
  pause: "pause",
  resume: "resume",
} as const

export interface BulkPipelineRequest {
  action: BulkPipelineAction
  /** @minItems 1 */
  run_ids: string[]
}

export interface BulkPipelineResponse {
  processed: number
  skipped: number
}

export interface BulkResultRequest {
  emails?: string[]
  all?: boolean
}

export interface BulkResultResponse {
  processed: number
}

export type CardBatchStatus =
  (typeof CardBatchStatus)[keyof typeof CardBatchStatus]

export const CardBatchStatus = {
  ready: "ready",
  consumed: "consumed",
  archived: "archived",
} as const

export interface CardInventoryItem {
  id: string
  code: string
  batch_id: string
  batch_name: string
  batch_status: CardBatchStatus
  position: number
  active: boolean
  run_count: number
  allocated_count: number
  created_count: number
  duplicate_count: number
  failed_count: number
  cached_charged: number | null
  cached_pending: number | null
  cached_remaining: number | null
  usage_error: string | null
  usage_checked_at: string | null
  created_at: string
}

export interface CardInventoryResponse {
  items: CardInventoryItem[]
  total: number
  limit: number
  offset: number
}

export interface CardInventoryStats {
  total: number
  active: number
  inactive: number
  batches: number
}

export interface CardSelectionRequest {
  /** @minimum 1 */
  target_count: number
}

export interface CardUsageItem {
  card_id: string
  code: string
  charged: number
  pending: number
  remaining: number
  error: string | null
}

export interface CardSelectionResponse {
  slots: string[]
  usage: CardUsageItem[]
}

export interface ClaimAccountRequest {
  email?: string | null
}

export interface DashboardJobStats {
  queued: number
  running: number
  failed: number
}

export interface DashboardPipelineStats {
  total: number
  active: number
  completed: number
  failed: number
}

export type PipelineStatus =
  (typeof PipelineStatus)[keyof typeof PipelineStatus]

export const PipelineStatus = {
  queued: "queued",
  running: "running",
  paused: "paused",
  completed: "completed",
  failed: "failed",
  canceled: "canceled",
} as const

export interface PipelineRunSummary {
  id: string
  status: PipelineStatus
  mode: string
  target_count: number
  kakao_enabled: boolean
  scheduled_count: number
  registered_count: number
  failed_count: number
  kakao_task_count: number
  started_at: string | null
  finished_at: string | null
  created_at: string
  updated_at: string
}

export interface DashboardResponse {
  accounts: AccountStats
  cards: CardInventoryStats
  pipelines: DashboardPipelineStats
  jobs: DashboardJobStats
  registration_results: number
}

export type RegistrationResultDetailMetadataJson = { [key: string]: unknown }

export interface RegistrationResultDetail {
  email: string
  password: string | null
  access_token: string | null
  session_token: string | null
  refresh_token: string | null
  id_token: string | null
  device_id: string | null
  cookie_header: string | null
  metadata_json: RegistrationResultDetailMetadataJson
  created_at: string
  updated_at: string
}

export interface ExportResultsResponse {
  items: RegistrationResultDetail[]
}

export interface ExportTargetSettings {
  enabled?: boolean
  url?: string
  /**
   * @minimum 5
   * @maximum 300
   */
  timeout?: number
  key_configured?: boolean
}

export interface ExportSettings {
  cpa?: ExportTargetSettings
  sub2api?: ExportTargetSettings
  sub2api_group_ids?: string
}

export interface ExportTargetUpdate {
  enabled?: boolean
  url?: string
  /**
   * @minimum 5
   * @maximum 300
   */
  timeout?: number
  key?: string
}

export interface ExportSettingsUpdate {
  cpa?: ExportTargetUpdate
  sub2api?: ExportTargetUpdate
  sub2api_group_ids?: string
}

export type ValidationErrorCtx = { [key: string]: unknown }

export interface ValidationError {
  loc: (string | number)[]
  msg: string
  type: string
  input?: unknown
  ctx?: ValidationErrorCtx
}

export interface HTTPValidationError {
  detail?: ValidationError[]
}

export interface HealthResponse {
  status: "ok"
  database: "ok"
  version: string
}

export interface ImportAccountsRequest {
  /** @minLength 1 */
  text: string
}

export interface ImportAccountsResponse {
  inserted: number
  updated: number
  unchanged: number
  invalid: number
  invalid_lines: number[]
}

export interface ImportCardsRequest {
  /** @minLength 1 */
  text: string
  /** @maxLength 128 */
  batch_name?: string
}

export interface ImportCardsResponse {
  batch_id: string | null
  inserted: number
  duplicates: number
}

export interface KakaoSettings {
  base_url?: string
  /**
   * @minimum 5
   * @maximum 300
   */
  timeout?: number
  /**
   * @minimum 1
   * @maximum 1000
   */
  card_usage_limit?: number
  plan_type?: "plus"
  promo_code?: string
}

export interface MailSettings {
  source?: "outlook" | "cf_temp"
  cf_api_url?: string
  cf_domain?: string
  cf_admin_token_configured?: boolean
}

export interface MailSettingsUpdate {
  source?: "outlook" | "cf_temp"
  cf_api_url?: string
  cf_domain?: string
  cf_admin_token?: string
}

export type KakaoTaskStatus =
  (typeof KakaoTaskStatus)[keyof typeof KakaoTaskStatus]

export const KakaoTaskStatus = {
  queued: "queued",
  extracting: "extracting",
  done: "done",
  failed: "failed",
  canceled: "canceled",
} as const

export interface KakaoTaskSummary {
  id: string
  upstream_job_id: string
  pipeline_run_id: string | null
  pipeline_item_id: string | null
  card_id: string
  email: string
  status: KakaoTaskStatus
  payment_status: string | null
  card_charged: boolean | null
  payment_url: string | null
  error: string | null
  created_at: string
  updated_at: string
}

export interface KakaoTaskListResponse {
  items: KakaoTaskSummary[]
  total: number
  limit: number
  offset: number
  pipeline_run_id: string | null
}

export interface PipelineCardAllocationSummary {
  card_id: string
  card_hint: string
  allocated_count: number
  created_count: number
  duplicate_count: number
  failed_count: number
}

export type PipelineItemStatus =
  (typeof PipelineItemStatus)[keyof typeof PipelineItemStatus]

export const PipelineItemStatus = {
  scheduled: "scheduled",
  registering: "registering",
  registered: "registered",
  submitting: "submitting",
  completed: "completed",
  skipped: "skipped",
  failed: "failed",
} as const

export interface PipelineItemSummary {
  id: string
  position: number
  account_email: string | null
  registration_run_id: string | null
  status: PipelineItemStatus
  eligibility_state: string | null
  error: string | null
  created_at: string
  updated_at: string
}

export type PipelineRunDetailConfigSnapshot = { [key: string]: unknown }

export interface PipelineRunDetail {
  id: string
  status: PipelineStatus
  mode: string
  target_count: number
  kakao_enabled: boolean
  scheduled_count: number
  registered_count: number
  failed_count: number
  kakao_task_count: number
  started_at: string | null
  finished_at: string | null
  created_at: string
  updated_at: string
  config_snapshot: PipelineRunDetailConfigSnapshot
  items: PipelineItemSummary[]
  cards: PipelineCardAllocationSummary[]
}

export interface PipelineRunListResponse {
  items: PipelineRunSummary[]
  total: number
  limit: number
  offset: number
}

export interface RegistrationResultSummary {
  email: string
  has_password: boolean
  has_access_token: boolean
  has_session_token: boolean
  has_refresh_token: boolean
  plus_eligible?: boolean | null
  plus_state?: string | null
  plus_error?: string | null
  plus_checked_at?: string | null
  created_at: string
  updated_at: string
}

export interface RegistrationResultListResponse {
  items: RegistrationResultSummary[]
  total: number
  limit: number
  offset: number
}

export interface RegistrationSettings {
  /**
   * @minimum 1
   * @maximum 50
   */
  concurrency?: number
  /**
   * @minimum 1
   * @maximum 300
   */
  otp_timeout?: number
  allow_existing_login?: boolean
  want_access_token?: boolean
  want_session_token?: boolean
  want_refresh_token?: boolean
  proxy?: string
  proxy_pool?: string
}

export type SmsSettingsProvider =
  (typeof SmsSettingsProvider)[keyof typeof SmsSettingsProvider]

export const SmsSettingsProvider = {
  smsbower: "smsbower",
  herosms: "herosms",
  grizzlysms: "grizzlysms",
} as const

export interface SmsSettings {
  enabled?: boolean
  provider?: SmsSettingsProvider
  country?: string
  service?: string
  max_price?: string
  reuse_phone?: boolean
  phone_success_max?: number
  auto_country?: boolean
  strict_whitelist?: boolean
  allowed_countries?: string
  auto_min_stock?: number
  auto_max_price?: string
  max_phone_attempts?: number
  per_phone_timeout?: number
  api_key_configured?: boolean
}

export type SmsSettingsUpdateProvider =
  (typeof SmsSettingsUpdateProvider)[keyof typeof SmsSettingsUpdateProvider]

export const SmsSettingsUpdateProvider = {
  smsbower: "smsbower",
  herosms: "herosms",
  grizzlysms: "grizzlysms",
} as const

export interface SmsSettingsUpdate {
  enabled?: boolean
  provider?: SmsSettingsUpdateProvider
  country?: string
  service?: string
  max_price?: string
  reuse_phone?: boolean
  phone_success_max?: number
  auto_country?: boolean
  strict_whitelist?: boolean
  allowed_countries?: string
  auto_min_stock?: number
  auto_max_price?: string
  max_phone_attempts?: number
  per_phone_timeout?: number
  api_key?: string
}

export interface SystemSettingsResponse {
  registration: RegistrationSettings
  mail: MailSettings
  kakao: KakaoSettings
  sms: SmsSettings
  export: ExportSettings
}

export interface SystemSettingsUpdate {
  registration: RegistrationSettings
  mail: MailSettingsUpdate
  kakao: KakaoSettings
  sms: SmsSettingsUpdate
  export: ExportSettingsUpdate
}

export type ListAccountsApiAccountsGetParams = {
  status?: AccountStatus | null
  search?: string
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: number
  /**
   * @minimum 0
   */
  offset?: number
}

export type ListCardsApiKakaoCardsGetParams = {
  active?: boolean | null
  search?: string
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: number
  /**
   * @minimum 0
   */
  offset?: number
}

export type ListPipelineRunsApiPipelinesRunsGetParams = {
  status?: PipelineStatus | null
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: number
  /**
   * @minimum 0
   */
  offset?: number
}

export type ListKakaoTasksApiKakaoTasksGetParams = {
  pipeline_run_id?: string | null
  status?: KakaoTaskStatus | null
  payment_status?: string
  search?: string
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: number
  /**
   * @minimum 0
   */
  offset?: number
}

export type ListResultsApiResultsGetParams = {
  search?: string
  token_filter?: ListResultsApiResultsGetTokenFilter
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: number
  /**
   * @minimum 0
   */
  offset?: number
}

export type ListResultsApiResultsGetTokenFilter =
  (typeof ListResultsApiResultsGetTokenFilter)[keyof typeof ListResultsApiResultsGetTokenFilter]

export const ListResultsApiResultsGetTokenFilter = {
  all: "all",
  access: "access",
  session: "session",
  refresh: "refresh",
  plus_eligible: "plus_eligible",
  plus_ineligible: "plus_ineligible",
  plus_unchecked: "plus_unchecked",
} as const

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K }
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    })
  }
  return result
}

/**
 * @summary Health
 */
export const healthApiHealthGet = (
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<HealthResponse>(
    { url: `/api/health`, method: "GET", signal },
    options
  )
}

export const getHealthApiHealthGetQueryKey = () => {
  return [`/api/health`] as const
}

export const getHealthApiHealthGetQueryOptions = <
  TData = Awaited<ReturnType<typeof healthApiHealthGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthApiHealthGet>>,
    TError,
    TData
  >
  request?: SecondParameter<typeof orvalRequest>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getHealthApiHealthGetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof healthApiHealthGet>>
  > = ({ signal }) => healthApiHealthGet(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthApiHealthGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type HealthApiHealthGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthApiHealthGet>>
>
export type HealthApiHealthGetQueryError = unknown

/**
 * @summary Health
 */

export function useHealthApiHealthGet<
  TData = Awaited<ReturnType<typeof healthApiHealthGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthApiHealthGet>>,
    TError,
    TData
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthApiHealthGetQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary List Accounts
 */
export const listAccountsApiAccountsGet = (
  params?: ListAccountsApiAccountsGetParams,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<AccountListResponse>(
    { url: `/api/accounts`, method: "GET", params, signal },
    options
  )
}

export const getListAccountsApiAccountsGetQueryKey = (
  params?: ListAccountsApiAccountsGetParams
) => {
  return [`/api/accounts`, ...(params ? [params] : [])] as const
}

export const getListAccountsApiAccountsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof listAccountsApiAccountsGet>>,
  TError = HTTPValidationError,
>(
  params?: ListAccountsApiAccountsGetParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listAccountsApiAccountsGet>>,
      TError,
      TData
    >
    request?: SecondParameter<typeof orvalRequest>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getListAccountsApiAccountsGetQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listAccountsApiAccountsGet>>
  > = ({ signal }) => listAccountsApiAccountsGet(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAccountsApiAccountsGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type ListAccountsApiAccountsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAccountsApiAccountsGet>>
>
export type ListAccountsApiAccountsGetQueryError = HTTPValidationError

/**
 * @summary List Accounts
 */

export function useListAccountsApiAccountsGet<
  TData = Awaited<ReturnType<typeof listAccountsApiAccountsGet>>,
  TError = HTTPValidationError,
>(
  params?: ListAccountsApiAccountsGetParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listAccountsApiAccountsGet>>,
      TError,
      TData
    >
    request?: SecondParameter<typeof orvalRequest>
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListAccountsApiAccountsGetQueryOptions(
    params,
    options
  )

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Get Account Stats
 */
export const getAccountStatsApiAccountsStatsGet = (
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<AccountStats>(
    { url: `/api/accounts/stats`, method: "GET", signal },
    options
  )
}

export const getGetAccountStatsApiAccountsStatsGetQueryKey = () => {
  return [`/api/accounts/stats`] as const
}

export const getGetAccountStatsApiAccountsStatsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getAccountStatsApiAccountsStatsGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAccountStatsApiAccountsStatsGet>>,
    TError,
    TData
  >
  request?: SecondParameter<typeof orvalRequest>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetAccountStatsApiAccountsStatsGetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAccountStatsApiAccountsStatsGet>>
  > = ({ signal }) => getAccountStatsApiAccountsStatsGet(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAccountStatsApiAccountsStatsGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetAccountStatsApiAccountsStatsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccountStatsApiAccountsStatsGet>>
>
export type GetAccountStatsApiAccountsStatsGetQueryError = unknown

/**
 * @summary Get Account Stats
 */

export function useGetAccountStatsApiAccountsStatsGet<
  TData = Awaited<ReturnType<typeof getAccountStatsApiAccountsStatsGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAccountStatsApiAccountsStatsGet>>,
    TError,
    TData
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions =
    getGetAccountStatsApiAccountsStatsGetQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Import Accounts
 */
export const importAccountsApiAccountsImportPost = (
  importAccountsRequest: ImportAccountsRequest,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<ImportAccountsResponse>(
    {
      url: `/api/accounts/import`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: importAccountsRequest,
      signal,
    },
    options
  )
}

export const getImportAccountsApiAccountsImportPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof importAccountsApiAccountsImportPost>>,
    TError,
    { data: ImportAccountsRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationOptions<
  Awaited<ReturnType<typeof importAccountsApiAccountsImportPost>>,
  TError,
  { data: ImportAccountsRequest },
  TContext
> => {
  const mutationKey = ["importAccountsApiAccountsImportPost"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof importAccountsApiAccountsImportPost>>,
    { data: ImportAccountsRequest }
  > = (props) => {
    const { data } = props ?? {}

    return importAccountsApiAccountsImportPost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ImportAccountsApiAccountsImportPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof importAccountsApiAccountsImportPost>>
>
export type ImportAccountsApiAccountsImportPostMutationBody =
  ImportAccountsRequest
export type ImportAccountsApiAccountsImportPostMutationError =
  HTTPValidationError

/**
 * @summary Import Accounts
 */
export const useImportAccountsApiAccountsImportPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof importAccountsApiAccountsImportPost>>,
    TError,
    { data: ImportAccountsRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationResult<
  Awaited<ReturnType<typeof importAccountsApiAccountsImportPost>>,
  TError,
  { data: ImportAccountsRequest },
  TContext
> => {
  return useMutation(
    getImportAccountsApiAccountsImportPostMutationOptions(options)
  )
}

/**
 * @summary Claim Account
 */
export const claimAccountApiAccountsClaimPost = (
  claimAccountRequest: ClaimAccountRequest,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<AccountDetail>(
    {
      url: `/api/accounts/claim`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: claimAccountRequest,
      signal,
    },
    options
  )
}

export const getClaimAccountApiAccountsClaimPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof claimAccountApiAccountsClaimPost>>,
    TError,
    { data: ClaimAccountRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationOptions<
  Awaited<ReturnType<typeof claimAccountApiAccountsClaimPost>>,
  TError,
  { data: ClaimAccountRequest },
  TContext
> => {
  const mutationKey = ["claimAccountApiAccountsClaimPost"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof claimAccountApiAccountsClaimPost>>,
    { data: ClaimAccountRequest }
  > = (props) => {
    const { data } = props ?? {}

    return claimAccountApiAccountsClaimPost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ClaimAccountApiAccountsClaimPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof claimAccountApiAccountsClaimPost>>
>
export type ClaimAccountApiAccountsClaimPostMutationBody = ClaimAccountRequest
export type ClaimAccountApiAccountsClaimPostMutationError = HTTPValidationError

/**
 * @summary Claim Account
 */
export const useClaimAccountApiAccountsClaimPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof claimAccountApiAccountsClaimPost>>,
    TError,
    { data: ClaimAccountRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationResult<
  Awaited<ReturnType<typeof claimAccountApiAccountsClaimPost>>,
  TError,
  { data: ClaimAccountRequest },
  TContext
> => {
  return useMutation(
    getClaimAccountApiAccountsClaimPostMutationOptions(options)
  )
}

/**
 * @summary Bulk Account Action
 */
export const bulkAccountActionApiAccountsBatchPost = (
  bulkAccountRequest: BulkAccountRequest,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<BulkAccountResponse>(
    {
      url: `/api/accounts/batch`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: bulkAccountRequest,
      signal,
    },
    options
  )
}

export const getBulkAccountActionApiAccountsBatchPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof bulkAccountActionApiAccountsBatchPost>>,
    TError,
    { data: BulkAccountRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationOptions<
  Awaited<ReturnType<typeof bulkAccountActionApiAccountsBatchPost>>,
  TError,
  { data: BulkAccountRequest },
  TContext
> => {
  const mutationKey = ["bulkAccountActionApiAccountsBatchPost"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof bulkAccountActionApiAccountsBatchPost>>,
    { data: BulkAccountRequest }
  > = (props) => {
    const { data } = props ?? {}

    return bulkAccountActionApiAccountsBatchPost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type BulkAccountActionApiAccountsBatchPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof bulkAccountActionApiAccountsBatchPost>>
>
export type BulkAccountActionApiAccountsBatchPostMutationBody =
  BulkAccountRequest
export type BulkAccountActionApiAccountsBatchPostMutationError =
  HTTPValidationError

/**
 * @summary Bulk Account Action
 */
export const useBulkAccountActionApiAccountsBatchPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof bulkAccountActionApiAccountsBatchPost>>,
    TError,
    { data: BulkAccountRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationResult<
  Awaited<ReturnType<typeof bulkAccountActionApiAccountsBatchPost>>,
  TError,
  { data: BulkAccountRequest },
  TContext
> => {
  return useMutation(
    getBulkAccountActionApiAccountsBatchPostMutationOptions(options)
  )
}

/**
 * @summary Maintain Accounts
 */
export const maintainAccountsApiAccountsMaintenancePost = (
  accountMaintenanceRequest: AccountMaintenanceRequest,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<AccountMaintenanceResponse>(
    {
      url: `/api/accounts/maintenance`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: accountMaintenanceRequest,
      signal,
    },
    options
  )
}

export const getMaintainAccountsApiAccountsMaintenancePostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof maintainAccountsApiAccountsMaintenancePost>>,
    TError,
    { data: AccountMaintenanceRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationOptions<
  Awaited<ReturnType<typeof maintainAccountsApiAccountsMaintenancePost>>,
  TError,
  { data: AccountMaintenanceRequest },
  TContext
> => {
  const mutationKey = ["maintainAccountsApiAccountsMaintenancePost"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof maintainAccountsApiAccountsMaintenancePost>>,
    { data: AccountMaintenanceRequest }
  > = (props) => {
    const { data } = props ?? {}

    return maintainAccountsApiAccountsMaintenancePost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type MaintainAccountsApiAccountsMaintenancePostMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof maintainAccountsApiAccountsMaintenancePost>>
  >
export type MaintainAccountsApiAccountsMaintenancePostMutationBody =
  AccountMaintenanceRequest
export type MaintainAccountsApiAccountsMaintenancePostMutationError =
  HTTPValidationError

/**
 * @summary Maintain Accounts
 */
export const useMaintainAccountsApiAccountsMaintenancePost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof maintainAccountsApiAccountsMaintenancePost>>,
    TError,
    { data: AccountMaintenanceRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationResult<
  Awaited<ReturnType<typeof maintainAccountsApiAccountsMaintenancePost>>,
  TError,
  { data: AccountMaintenanceRequest },
  TContext
> => {
  return useMutation(
    getMaintainAccountsApiAccountsMaintenancePostMutationOptions(options)
  )
}

/**
 * @summary Get Account
 */
export const getAccountApiAccountsEmailGet = (
  email: string,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<AccountDetail>(
    { url: `/api/accounts/${email}`, method: "GET", signal },
    options
  )
}

export const getGetAccountApiAccountsEmailGetQueryKey = (email: string) => {
  return [`/api/accounts/${email}`] as const
}

export const getGetAccountApiAccountsEmailGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getAccountApiAccountsEmailGet>>,
  TError = HTTPValidationError,
>(
  email: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getAccountApiAccountsEmailGet>>,
      TError,
      TData
    >
    request?: SecondParameter<typeof orvalRequest>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetAccountApiAccountsEmailGetQueryKey(email)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAccountApiAccountsEmailGet>>
  > = ({ signal }) =>
    getAccountApiAccountsEmailGet(email, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: email !== null && email !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAccountApiAccountsEmailGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetAccountApiAccountsEmailGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccountApiAccountsEmailGet>>
>
export type GetAccountApiAccountsEmailGetQueryError = HTTPValidationError

/**
 * @summary Get Account
 */

export function useGetAccountApiAccountsEmailGet<
  TData = Awaited<ReturnType<typeof getAccountApiAccountsEmailGet>>,
  TError = HTTPValidationError,
>(
  email: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getAccountApiAccountsEmailGet>>,
      TError,
      TData
    >
    request?: SecondParameter<typeof orvalRequest>
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetAccountApiAccountsEmailGetQueryOptions(
    email,
    options
  )

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Delete Account
 */
export const deleteAccountApiAccountsEmailDelete = (
  email: string,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<void>(
    { url: `/api/accounts/${email}`, method: "DELETE", signal },
    options
  )
}

export const getDeleteAccountApiAccountsEmailDeleteMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAccountApiAccountsEmailDelete>>,
    TError,
    { email: string },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAccountApiAccountsEmailDelete>>,
  TError,
  { email: string },
  TContext
> => {
  const mutationKey = ["deleteAccountApiAccountsEmailDelete"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAccountApiAccountsEmailDelete>>,
    { email: string }
  > = (props) => {
    const { email } = props ?? {}

    return deleteAccountApiAccountsEmailDelete(email, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteAccountApiAccountsEmailDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAccountApiAccountsEmailDelete>>
>

export type DeleteAccountApiAccountsEmailDeleteMutationError =
  HTTPValidationError

/**
 * @summary Delete Account
 */
export const useDeleteAccountApiAccountsEmailDelete = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAccountApiAccountsEmailDelete>>,
    TError,
    { email: string },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteAccountApiAccountsEmailDelete>>,
  TError,
  { email: string },
  TContext
> => {
  return useMutation(
    getDeleteAccountApiAccountsEmailDeleteMutationOptions(options)
  )
}

/**
 * @summary Release Account
 */
export const releaseAccountApiAccountsEmailReleasePost = (
  email: string,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<AccountDetail>(
    { url: `/api/accounts/${email}/release`, method: "POST", signal },
    options
  )
}

export const getReleaseAccountApiAccountsEmailReleasePostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof releaseAccountApiAccountsEmailReleasePost>>,
    TError,
    { email: string },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationOptions<
  Awaited<ReturnType<typeof releaseAccountApiAccountsEmailReleasePost>>,
  TError,
  { email: string },
  TContext
> => {
  const mutationKey = ["releaseAccountApiAccountsEmailReleasePost"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof releaseAccountApiAccountsEmailReleasePost>>,
    { email: string }
  > = (props) => {
    const { email } = props ?? {}

    return releaseAccountApiAccountsEmailReleasePost(email, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ReleaseAccountApiAccountsEmailReleasePostMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof releaseAccountApiAccountsEmailReleasePost>>
  >

export type ReleaseAccountApiAccountsEmailReleasePostMutationError =
  HTTPValidationError

/**
 * @summary Release Account
 */
export const useReleaseAccountApiAccountsEmailReleasePost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof releaseAccountApiAccountsEmailReleasePost>>,
    TError,
    { email: string },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationResult<
  Awaited<ReturnType<typeof releaseAccountApiAccountsEmailReleasePost>>,
  TError,
  { email: string },
  TContext
> => {
  return useMutation(
    getReleaseAccountApiAccountsEmailReleasePostMutationOptions(options)
  )
}

/**
 * @summary Reset Account
 */
export const resetAccountApiAccountsEmailResetPost = (
  email: string,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<AccountDetail>(
    { url: `/api/accounts/${email}/reset`, method: "POST", signal },
    options
  )
}

export const getResetAccountApiAccountsEmailResetPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resetAccountApiAccountsEmailResetPost>>,
    TError,
    { email: string },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationOptions<
  Awaited<ReturnType<typeof resetAccountApiAccountsEmailResetPost>>,
  TError,
  { email: string },
  TContext
> => {
  const mutationKey = ["resetAccountApiAccountsEmailResetPost"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof resetAccountApiAccountsEmailResetPost>>,
    { email: string }
  > = (props) => {
    const { email } = props ?? {}

    return resetAccountApiAccountsEmailResetPost(email, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ResetAccountApiAccountsEmailResetPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof resetAccountApiAccountsEmailResetPost>>
>

export type ResetAccountApiAccountsEmailResetPostMutationError =
  HTTPValidationError

/**
 * @summary Reset Account
 */
export const useResetAccountApiAccountsEmailResetPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resetAccountApiAccountsEmailResetPost>>,
    TError,
    { email: string },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationResult<
  Awaited<ReturnType<typeof resetAccountApiAccountsEmailResetPost>>,
  TError,
  { email: string },
  TContext
> => {
  return useMutation(
    getResetAccountApiAccountsEmailResetPostMutationOptions(options)
  )
}

/**
 * @summary List Cards
 */
export const listCardsApiKakaoCardsGet = (
  params?: ListCardsApiKakaoCardsGetParams,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<CardInventoryResponse>(
    { url: `/api/kakao/cards`, method: "GET", params, signal },
    options
  )
}

export const getListCardsApiKakaoCardsGetQueryKey = (
  params?: ListCardsApiKakaoCardsGetParams
) => {
  return [`/api/kakao/cards`, ...(params ? [params] : [])] as const
}

export const getListCardsApiKakaoCardsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof listCardsApiKakaoCardsGet>>,
  TError = HTTPValidationError,
>(
  params?: ListCardsApiKakaoCardsGetParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listCardsApiKakaoCardsGet>>,
      TError,
      TData
    >
    request?: SecondParameter<typeof orvalRequest>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getListCardsApiKakaoCardsGetQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listCardsApiKakaoCardsGet>>
  > = ({ signal }) => listCardsApiKakaoCardsGet(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listCardsApiKakaoCardsGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type ListCardsApiKakaoCardsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof listCardsApiKakaoCardsGet>>
>
export type ListCardsApiKakaoCardsGetQueryError = HTTPValidationError

/**
 * @summary List Cards
 */

export function useListCardsApiKakaoCardsGet<
  TData = Awaited<ReturnType<typeof listCardsApiKakaoCardsGet>>,
  TError = HTTPValidationError,
>(
  params?: ListCardsApiKakaoCardsGetParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listCardsApiKakaoCardsGet>>,
      TError,
      TData
    >
    request?: SecondParameter<typeof orvalRequest>
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListCardsApiKakaoCardsGetQueryOptions(params, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Get Card Stats
 */
export const getCardStatsApiKakaoCardsStatsGet = (
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<CardInventoryStats>(
    { url: `/api/kakao/cards/stats`, method: "GET", signal },
    options
  )
}

export const getGetCardStatsApiKakaoCardsStatsGetQueryKey = () => {
  return [`/api/kakao/cards/stats`] as const
}

export const getGetCardStatsApiKakaoCardsStatsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getCardStatsApiKakaoCardsStatsGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCardStatsApiKakaoCardsStatsGet>>,
    TError,
    TData
  >
  request?: SecondParameter<typeof orvalRequest>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetCardStatsApiKakaoCardsStatsGetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCardStatsApiKakaoCardsStatsGet>>
  > = ({ signal }) => getCardStatsApiKakaoCardsStatsGet(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCardStatsApiKakaoCardsStatsGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetCardStatsApiKakaoCardsStatsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCardStatsApiKakaoCardsStatsGet>>
>
export type GetCardStatsApiKakaoCardsStatsGetQueryError = unknown

/**
 * @summary Get Card Stats
 */

export function useGetCardStatsApiKakaoCardsStatsGet<
  TData = Awaited<ReturnType<typeof getCardStatsApiKakaoCardsStatsGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCardStatsApiKakaoCardsStatsGet>>,
    TError,
    TData
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCardStatsApiKakaoCardsStatsGetQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Import Cards
 */
export const importCardsApiKakaoCardsImportPost = (
  importCardsRequest: ImportCardsRequest,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<ImportCardsResponse>(
    {
      url: `/api/kakao/cards/import`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: importCardsRequest,
      signal,
    },
    options
  )
}

export const getImportCardsApiKakaoCardsImportPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof importCardsApiKakaoCardsImportPost>>,
    TError,
    { data: ImportCardsRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationOptions<
  Awaited<ReturnType<typeof importCardsApiKakaoCardsImportPost>>,
  TError,
  { data: ImportCardsRequest },
  TContext
> => {
  const mutationKey = ["importCardsApiKakaoCardsImportPost"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof importCardsApiKakaoCardsImportPost>>,
    { data: ImportCardsRequest }
  > = (props) => {
    const { data } = props ?? {}

    return importCardsApiKakaoCardsImportPost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ImportCardsApiKakaoCardsImportPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof importCardsApiKakaoCardsImportPost>>
>
export type ImportCardsApiKakaoCardsImportPostMutationBody = ImportCardsRequest
export type ImportCardsApiKakaoCardsImportPostMutationError =
  HTTPValidationError

/**
 * @summary Import Cards
 */
export const useImportCardsApiKakaoCardsImportPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof importCardsApiKakaoCardsImportPost>>,
    TError,
    { data: ImportCardsRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationResult<
  Awaited<ReturnType<typeof importCardsApiKakaoCardsImportPost>>,
  TError,
  { data: ImportCardsRequest },
  TContext
> => {
  return useMutation(
    getImportCardsApiKakaoCardsImportPostMutationOptions(options)
  )
}

/**
 * @summary Bulk Card Action
 */
export const bulkCardActionApiKakaoCardsBatchPost = (
  bulkCardRequest: BulkCardRequest,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<BulkCardResponse>(
    {
      url: `/api/kakao/cards/batch`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: bulkCardRequest,
      signal,
    },
    options
  )
}

export const getBulkCardActionApiKakaoCardsBatchPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof bulkCardActionApiKakaoCardsBatchPost>>,
    TError,
    { data: BulkCardRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationOptions<
  Awaited<ReturnType<typeof bulkCardActionApiKakaoCardsBatchPost>>,
  TError,
  { data: BulkCardRequest },
  TContext
> => {
  const mutationKey = ["bulkCardActionApiKakaoCardsBatchPost"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof bulkCardActionApiKakaoCardsBatchPost>>,
    { data: BulkCardRequest }
  > = (props) => {
    const { data } = props ?? {}

    return bulkCardActionApiKakaoCardsBatchPost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type BulkCardActionApiKakaoCardsBatchPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof bulkCardActionApiKakaoCardsBatchPost>>
>
export type BulkCardActionApiKakaoCardsBatchPostMutationBody = BulkCardRequest
export type BulkCardActionApiKakaoCardsBatchPostMutationError =
  HTTPValidationError

/**
 * @summary Bulk Card Action
 */
export const useBulkCardActionApiKakaoCardsBatchPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof bulkCardActionApiKakaoCardsBatchPost>>,
    TError,
    { data: BulkCardRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationResult<
  Awaited<ReturnType<typeof bulkCardActionApiKakaoCardsBatchPost>>,
  TError,
  { data: BulkCardRequest },
  TContext
> => {
  return useMutation(
    getBulkCardActionApiKakaoCardsBatchPostMutationOptions(options)
  )
}

/**
 * @summary Select Cards
 */
export const selectCardsApiKakaoCardsSelectPost = (
  cardSelectionRequest: CardSelectionRequest,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<CardSelectionResponse>(
    {
      url: `/api/kakao/cards/select`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: cardSelectionRequest,
      signal,
    },
    options
  )
}

export const getSelectCardsApiKakaoCardsSelectPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof selectCardsApiKakaoCardsSelectPost>>,
    TError,
    { data: CardSelectionRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationOptions<
  Awaited<ReturnType<typeof selectCardsApiKakaoCardsSelectPost>>,
  TError,
  { data: CardSelectionRequest },
  TContext
> => {
  const mutationKey = ["selectCardsApiKakaoCardsSelectPost"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof selectCardsApiKakaoCardsSelectPost>>,
    { data: CardSelectionRequest }
  > = (props) => {
    const { data } = props ?? {}

    return selectCardsApiKakaoCardsSelectPost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type SelectCardsApiKakaoCardsSelectPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof selectCardsApiKakaoCardsSelectPost>>
>
export type SelectCardsApiKakaoCardsSelectPostMutationBody =
  CardSelectionRequest
export type SelectCardsApiKakaoCardsSelectPostMutationError =
  HTTPValidationError

/**
 * @summary Select Cards
 */
export const useSelectCardsApiKakaoCardsSelectPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof selectCardsApiKakaoCardsSelectPost>>,
    TError,
    { data: CardSelectionRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationResult<
  Awaited<ReturnType<typeof selectCardsApiKakaoCardsSelectPost>>,
  TError,
  { data: CardSelectionRequest },
  TContext
> => {
  return useMutation(
    getSelectCardsApiKakaoCardsSelectPostMutationOptions(options)
  )
}

/**
 * @summary Get Dashboard
 */
export const getDashboardApiDashboardGet = (
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<DashboardResponse>(
    { url: `/api/dashboard`, method: "GET", signal },
    options
  )
}

export const getGetDashboardApiDashboardGetQueryKey = () => {
  return [`/api/dashboard`] as const
}

export const getGetDashboardApiDashboardGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getDashboardApiDashboardGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardApiDashboardGet>>,
    TError,
    TData
  >
  request?: SecondParameter<typeof orvalRequest>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetDashboardApiDashboardGetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDashboardApiDashboardGet>>
  > = ({ signal }) => getDashboardApiDashboardGet(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardApiDashboardGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetDashboardApiDashboardGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDashboardApiDashboardGet>>
>
export type GetDashboardApiDashboardGetQueryError = unknown

/**
 * @summary Get Dashboard
 */

export function useGetDashboardApiDashboardGet<
  TData = Awaited<ReturnType<typeof getDashboardApiDashboardGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardApiDashboardGet>>,
    TError,
    TData
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetDashboardApiDashboardGetQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary List Pipeline Runs
 */
export const listPipelineRunsApiPipelinesRunsGet = (
  params?: ListPipelineRunsApiPipelinesRunsGetParams,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<PipelineRunListResponse>(
    { url: `/api/pipelines/runs`, method: "GET", params, signal },
    options
  )
}

export const getListPipelineRunsApiPipelinesRunsGetQueryKey = (
  params?: ListPipelineRunsApiPipelinesRunsGetParams
) => {
  return [`/api/pipelines/runs`, ...(params ? [params] : [])] as const
}

export const getListPipelineRunsApiPipelinesRunsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof listPipelineRunsApiPipelinesRunsGet>>,
  TError = HTTPValidationError,
>(
  params?: ListPipelineRunsApiPipelinesRunsGetParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listPipelineRunsApiPipelinesRunsGet>>,
      TError,
      TData
    >
    request?: SecondParameter<typeof orvalRequest>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getListPipelineRunsApiPipelinesRunsGetQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listPipelineRunsApiPipelinesRunsGet>>
  > = ({ signal }) =>
    listPipelineRunsApiPipelinesRunsGet(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listPipelineRunsApiPipelinesRunsGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type ListPipelineRunsApiPipelinesRunsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPipelineRunsApiPipelinesRunsGet>>
>
export type ListPipelineRunsApiPipelinesRunsGetQueryError = HTTPValidationError

/**
 * @summary List Pipeline Runs
 */

export function useListPipelineRunsApiPipelinesRunsGet<
  TData = Awaited<ReturnType<typeof listPipelineRunsApiPipelinesRunsGet>>,
  TError = HTTPValidationError,
>(
  params?: ListPipelineRunsApiPipelinesRunsGetParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listPipelineRunsApiPipelinesRunsGet>>,
      TError,
      TData
    >
    request?: SecondParameter<typeof orvalRequest>
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListPipelineRunsApiPipelinesRunsGetQueryOptions(
    params,
    options
  )

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Bulk Pipeline Action
 */
export const bulkPipelineActionApiPipelinesRunsBatchPost = (
  bulkPipelineRequest: BulkPipelineRequest,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<BulkPipelineResponse>(
    {
      url: `/api/pipelines/runs/batch`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: bulkPipelineRequest,
      signal,
    },
    options
  )
}

export const getBulkPipelineActionApiPipelinesRunsBatchPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof bulkPipelineActionApiPipelinesRunsBatchPost>>,
    TError,
    { data: BulkPipelineRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationOptions<
  Awaited<ReturnType<typeof bulkPipelineActionApiPipelinesRunsBatchPost>>,
  TError,
  { data: BulkPipelineRequest },
  TContext
> => {
  const mutationKey = ["bulkPipelineActionApiPipelinesRunsBatchPost"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof bulkPipelineActionApiPipelinesRunsBatchPost>>,
    { data: BulkPipelineRequest }
  > = (props) => {
    const { data } = props ?? {}

    return bulkPipelineActionApiPipelinesRunsBatchPost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type BulkPipelineActionApiPipelinesRunsBatchPostMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof bulkPipelineActionApiPipelinesRunsBatchPost>>
  >
export type BulkPipelineActionApiPipelinesRunsBatchPostMutationBody =
  BulkPipelineRequest
export type BulkPipelineActionApiPipelinesRunsBatchPostMutationError =
  HTTPValidationError

/**
 * @summary Bulk Pipeline Action
 */
export const useBulkPipelineActionApiPipelinesRunsBatchPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof bulkPipelineActionApiPipelinesRunsBatchPost>>,
    TError,
    { data: BulkPipelineRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationResult<
  Awaited<ReturnType<typeof bulkPipelineActionApiPipelinesRunsBatchPost>>,
  TError,
  { data: BulkPipelineRequest },
  TContext
> => {
  return useMutation(
    getBulkPipelineActionApiPipelinesRunsBatchPostMutationOptions(options)
  )
}

/**
 * @summary Get Pipeline Run
 */
export const getPipelineRunApiPipelinesRunsRunIdGet = (
  runId: string,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<PipelineRunDetail>(
    { url: `/api/pipelines/runs/${runId}`, method: "GET", signal },
    options
  )
}

export const getGetPipelineRunApiPipelinesRunsRunIdGetQueryKey = (
  runId: string
) => {
  return [`/api/pipelines/runs/${runId}`] as const
}

export const getGetPipelineRunApiPipelinesRunsRunIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getPipelineRunApiPipelinesRunsRunIdGet>>,
  TError = HTTPValidationError,
>(
  runId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getPipelineRunApiPipelinesRunsRunIdGet>>,
      TError,
      TData
    >
    request?: SecondParameter<typeof orvalRequest>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getGetPipelineRunApiPipelinesRunsRunIdGetQueryKey(runId)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPipelineRunApiPipelinesRunsRunIdGet>>
  > = ({ signal }) =>
    getPipelineRunApiPipelinesRunsRunIdGet(runId, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: runId !== null && runId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPipelineRunApiPipelinesRunsRunIdGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetPipelineRunApiPipelinesRunsRunIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPipelineRunApiPipelinesRunsRunIdGet>>
>
export type GetPipelineRunApiPipelinesRunsRunIdGetQueryError =
  HTTPValidationError

/**
 * @summary Get Pipeline Run
 */

export function useGetPipelineRunApiPipelinesRunsRunIdGet<
  TData = Awaited<ReturnType<typeof getPipelineRunApiPipelinesRunsRunIdGet>>,
  TError = HTTPValidationError,
>(
  runId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getPipelineRunApiPipelinesRunsRunIdGet>>,
      TError,
      TData
    >
    request?: SecondParameter<typeof orvalRequest>
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetPipelineRunApiPipelinesRunsRunIdGetQueryOptions(
    runId,
    options
  )

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary List Kakao Tasks
 */
export const listKakaoTasksApiKakaoTasksGet = (
  params?: ListKakaoTasksApiKakaoTasksGetParams,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<KakaoTaskListResponse>(
    { url: `/api/kakao/tasks`, method: "GET", params, signal },
    options
  )
}

export const getListKakaoTasksApiKakaoTasksGetQueryKey = (
  params?: ListKakaoTasksApiKakaoTasksGetParams
) => {
  return [`/api/kakao/tasks`, ...(params ? [params] : [])] as const
}

export const getListKakaoTasksApiKakaoTasksGetQueryOptions = <
  TData = Awaited<ReturnType<typeof listKakaoTasksApiKakaoTasksGet>>,
  TError = HTTPValidationError,
>(
  params?: ListKakaoTasksApiKakaoTasksGetParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listKakaoTasksApiKakaoTasksGet>>,
      TError,
      TData
    >
    request?: SecondParameter<typeof orvalRequest>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getListKakaoTasksApiKakaoTasksGetQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listKakaoTasksApiKakaoTasksGet>>
  > = ({ signal }) =>
    listKakaoTasksApiKakaoTasksGet(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listKakaoTasksApiKakaoTasksGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type ListKakaoTasksApiKakaoTasksGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof listKakaoTasksApiKakaoTasksGet>>
>
export type ListKakaoTasksApiKakaoTasksGetQueryError = HTTPValidationError

/**
 * @summary List Kakao Tasks
 */

export function useListKakaoTasksApiKakaoTasksGet<
  TData = Awaited<ReturnType<typeof listKakaoTasksApiKakaoTasksGet>>,
  TError = HTTPValidationError,
>(
  params?: ListKakaoTasksApiKakaoTasksGetParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listKakaoTasksApiKakaoTasksGet>>,
      TError,
      TData
    >
    request?: SecondParameter<typeof orvalRequest>
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListKakaoTasksApiKakaoTasksGetQueryOptions(
    params,
    options
  )

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary List Results
 */
export const listResultsApiResultsGet = (
  params?: ListResultsApiResultsGetParams,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<RegistrationResultListResponse>(
    { url: `/api/results`, method: "GET", params, signal },
    options
  )
}

export const getListResultsApiResultsGetQueryKey = (
  params?: ListResultsApiResultsGetParams
) => {
  return [`/api/results`, ...(params ? [params] : [])] as const
}

export const getListResultsApiResultsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof listResultsApiResultsGet>>,
  TError = HTTPValidationError,
>(
  params?: ListResultsApiResultsGetParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listResultsApiResultsGet>>,
      TError,
      TData
    >
    request?: SecondParameter<typeof orvalRequest>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getListResultsApiResultsGetQueryKey(params)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listResultsApiResultsGet>>
  > = ({ signal }) => listResultsApiResultsGet(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listResultsApiResultsGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type ListResultsApiResultsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof listResultsApiResultsGet>>
>
export type ListResultsApiResultsGetQueryError = HTTPValidationError

/**
 * @summary List Results
 */

export function useListResultsApiResultsGet<
  TData = Awaited<ReturnType<typeof listResultsApiResultsGet>>,
  TError = HTTPValidationError,
>(
  params?: ListResultsApiResultsGetParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listResultsApiResultsGet>>,
      TError,
      TData
    >
    request?: SecondParameter<typeof orvalRequest>
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListResultsApiResultsGetQueryOptions(params, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Export Results
 */
export const exportResultsApiResultsExportPost = (
  bulkResultRequest: BulkResultRequest,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<ExportResultsResponse>(
    {
      url: `/api/results/export`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: bulkResultRequest,
      signal,
    },
    options
  )
}

export const getExportResultsApiResultsExportPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof exportResultsApiResultsExportPost>>,
    TError,
    { data: BulkResultRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationOptions<
  Awaited<ReturnType<typeof exportResultsApiResultsExportPost>>,
  TError,
  { data: BulkResultRequest },
  TContext
> => {
  const mutationKey = ["exportResultsApiResultsExportPost"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof exportResultsApiResultsExportPost>>,
    { data: BulkResultRequest }
  > = (props) => {
    const { data } = props ?? {}

    return exportResultsApiResultsExportPost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ExportResultsApiResultsExportPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof exportResultsApiResultsExportPost>>
>
export type ExportResultsApiResultsExportPostMutationBody = BulkResultRequest
export type ExportResultsApiResultsExportPostMutationError = HTTPValidationError

/**
 * @summary Export Results
 */
export const useExportResultsApiResultsExportPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof exportResultsApiResultsExportPost>>,
    TError,
    { data: BulkResultRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationResult<
  Awaited<ReturnType<typeof exportResultsApiResultsExportPost>>,
  TError,
  { data: BulkResultRequest },
  TContext
> => {
  return useMutation(
    getExportResultsApiResultsExportPostMutationOptions(options)
  )
}

/**
 * @summary Delete Results
 */
export const deleteResultsApiResultsBatchDeletePost = (
  bulkResultRequest: BulkResultRequest,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<BulkResultResponse>(
    {
      url: `/api/results/batch-delete`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: bulkResultRequest,
      signal,
    },
    options
  )
}

export const getDeleteResultsApiResultsBatchDeletePostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteResultsApiResultsBatchDeletePost>>,
    TError,
    { data: BulkResultRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteResultsApiResultsBatchDeletePost>>,
  TError,
  { data: BulkResultRequest },
  TContext
> => {
  const mutationKey = ["deleteResultsApiResultsBatchDeletePost"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteResultsApiResultsBatchDeletePost>>,
    { data: BulkResultRequest }
  > = (props) => {
    const { data } = props ?? {}

    return deleteResultsApiResultsBatchDeletePost(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteResultsApiResultsBatchDeletePostMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteResultsApiResultsBatchDeletePost>>
>
export type DeleteResultsApiResultsBatchDeletePostMutationBody =
  BulkResultRequest
export type DeleteResultsApiResultsBatchDeletePostMutationError =
  HTTPValidationError

/**
 * @summary Delete Results
 */
export const useDeleteResultsApiResultsBatchDeletePost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteResultsApiResultsBatchDeletePost>>,
    TError,
    { data: BulkResultRequest },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteResultsApiResultsBatchDeletePost>>,
  TError,
  { data: BulkResultRequest },
  TContext
> => {
  return useMutation(
    getDeleteResultsApiResultsBatchDeletePostMutationOptions(options)
  )
}

/**
 * @summary Get Result
 */
export const getResultApiResultsEmailGet = (
  email: string,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<RegistrationResultDetail>(
    { url: `/api/results/${email}`, method: "GET", signal },
    options
  )
}

export const getGetResultApiResultsEmailGetQueryKey = (email: string) => {
  return [`/api/results/${email}`] as const
}

export const getGetResultApiResultsEmailGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getResultApiResultsEmailGet>>,
  TError = HTTPValidationError,
>(
  email: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getResultApiResultsEmailGet>>,
      TError,
      TData
    >
    request?: SecondParameter<typeof orvalRequest>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetResultApiResultsEmailGetQueryKey(email)

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getResultApiResultsEmailGet>>
  > = ({ signal }) => getResultApiResultsEmailGet(email, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: email !== null && email !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getResultApiResultsEmailGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetResultApiResultsEmailGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getResultApiResultsEmailGet>>
>
export type GetResultApiResultsEmailGetQueryError = HTTPValidationError

/**
 * @summary Get Result
 */

export function useGetResultApiResultsEmailGet<
  TData = Awaited<ReturnType<typeof getResultApiResultsEmailGet>>,
  TError = HTTPValidationError,
>(
  email: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getResultApiResultsEmailGet>>,
      TError,
      TData
    >
    request?: SecondParameter<typeof orvalRequest>
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetResultApiResultsEmailGetQueryOptions(
    email,
    options
  )

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Get Settings
 */
export const getSettingsApiSettingsGet = (
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<SystemSettingsResponse>(
    { url: `/api/settings`, method: "GET", signal },
    options
  )
}

export const getGetSettingsApiSettingsGetQueryKey = () => {
  return [`/api/settings`] as const
}

export const getGetSettingsApiSettingsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getSettingsApiSettingsGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSettingsApiSettingsGet>>,
    TError,
    TData
  >
  request?: SecondParameter<typeof orvalRequest>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getGetSettingsApiSettingsGetQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSettingsApiSettingsGet>>
  > = ({ signal }) => getSettingsApiSettingsGet(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSettingsApiSettingsGet>>,
    TError,
    TData
  > & { queryKey: QueryKey }
}

export type GetSettingsApiSettingsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSettingsApiSettingsGet>>
>
export type GetSettingsApiSettingsGetQueryError = unknown

/**
 * @summary Get Settings
 */

export function useGetSettingsApiSettingsGet<
  TData = Awaited<ReturnType<typeof getSettingsApiSettingsGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSettingsApiSettingsGet>>,
    TError,
    TData
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetSettingsApiSettingsGetQueryOptions(options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey
  }

  return withQueryKey(query, queryOptions.queryKey)
}

/**
 * @summary Update Settings
 */
export const updateSettingsApiSettingsPut = (
  systemSettingsUpdate: SystemSettingsUpdate,
  options?: SecondParameter<typeof orvalRequest>,
  signal?: AbortSignal
) => {
  return orvalRequest<SystemSettingsResponse>(
    {
      url: `/api/settings`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: systemSettingsUpdate,
      signal,
    },
    options
  )
}

export const getUpdateSettingsApiSettingsPutMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSettingsApiSettingsPut>>,
    TError,
    { data: SystemSettingsUpdate },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateSettingsApiSettingsPut>>,
  TError,
  { data: SystemSettingsUpdate },
  TContext
> => {
  const mutationKey = ["updateSettingsApiSettingsPut"]
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateSettingsApiSettingsPut>>,
    { data: SystemSettingsUpdate }
  > = (props) => {
    const { data } = props ?? {}

    return updateSettingsApiSettingsPut(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateSettingsApiSettingsPutMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateSettingsApiSettingsPut>>
>
export type UpdateSettingsApiSettingsPutMutationBody = SystemSettingsUpdate
export type UpdateSettingsApiSettingsPutMutationError = HTTPValidationError

/**
 * @summary Update Settings
 */
export const useUpdateSettingsApiSettingsPut = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSettingsApiSettingsPut>>,
    TError,
    { data: SystemSettingsUpdate },
    TContext
  >
  request?: SecondParameter<typeof orvalRequest>
}): UseMutationResult<
  Awaited<ReturnType<typeof updateSettingsApiSettingsPut>>,
  TError,
  { data: SystemSettingsUpdate },
  TContext
> => {
  return useMutation(getUpdateSettingsApiSettingsPutMutationOptions(options))
}
